server:
  port: 8888
  servlet:
    context-path: /office
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MYSQL 6+ 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MYSQL 5 驱动
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 连接池配置
    druid:
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 60
    # 配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存时间
    min-evictable-idle-time-millis: 300000
jetcache:
  areaInCacheName: false
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 172.17.63.0
      port: 6379
      #password:
